version: '3'
services:
  proxy:
    build:
      context: ./
      dockerfile: ./docker/proxy/Dockerfile
    ports:
      - 3001:80
    volumes:
      - ./rails/coverage:/app/coverage
    depends_on:
      - rails
      - nuxt
    restart: always

  rails:
    build:
      context: ./
      dockerfile: ./docker/rails/Dockerfile
    env_file:
      - ./compose.env
    ports:
      - 3000
    volumes:
      - ./rails:/app
    depends_on:
      - mysql
    restart: always

  nuxt:
    build:
      context: ./
      dockerfile: ./docker/nuxt/Dockerfile
    env_file:
      - ./compose.env
    ports:
      - 3000
    volumes:
      - ./nuxt:/app
    depends_on:
      - rails
    restart: always

  mysql:
    image: mysql:5.7
    env_file:
      - ./compose.env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  jekyll:
    image: jekyll/jekyll
    volumes:
      - ./jekyll:/usr/src/app
      - ./docs:/srv/jekyll/_site
    command: sh -c 'jekyll serve -s /usr/src/app --watch'
    ports:
      - 4000
    restart: always
volumes:
  mysql-data:
    driver: local
