version: '3'
services:
  proxy:
    build:
      context: ./
      dockerfile: ./docker/proxy/Dockerfile
    ports:
      - 3001:80
    volumes:
      - ./rails/coverage:/app/coverage
      - ./schemaspy/output:/app/schemaspy
      - ./docs:/app/practice
    restart: always
    depends_on:
      - rails
      - nuxt
      - jekyll

  rails:
    build:
      context: ./
      dockerfile: ./docker/rails/Dockerfile
    env_file:
      - ./compose.env
    ports:
      - 3000
    volumes:
      - ./rails:/app
    depends_on:
      - mysql
    restart: always
  redis:
    image: redis:latest
    ports:
      - 6379
  nuxt:
    build:
      context: ./
      dockerfile: ./docker/nuxt/Dockerfile
    env_file:
      - ./compose.env
    ports:
      - 3000
    volumes:
      - ./nuxt:/app
    depends_on:
      - rails
    restart: always

  mysql:
    image: mysql:5.7
    env_file:
      - ./compose.env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  jekyll:
    image: jekyll/jekyll
    volumes:
      - ./jekyll:/usr/src/app
      - ./docs:/srv/jekyll/_site
    command: jekyll serve -s /usr/src/app --watch --force_polling --livereload
    ports:
      - 4000:4000
      - 35729:35729
    restart: always

  schemaspy:
    image: schemaspy/schemaspy
    env_file:
      - ./compose.env
    volumes:
      - ./schemaspy/output:/output
      - ./schemaspy/config:/config
    command: ["-configFile", "/config/schemaspy.properties"]
    links:
      - mysql
volumes:
  mysql-data:
    driver: local
