require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: enable
Rails:
  Enabled: true

# frozen_string_literalのシミュレーションを行わない
Style/FrozenStringLiteralComment:
  Enabled: false

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# ドキュメンテーションを必須にしない
Style/Documentation:
  Enabled: false

# Spec内ではBlockの長さを制限しない
Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'spec/*'
    - 'spec/**/*'

# 文字列フォーマットはパーセント表記
FormatString:
  EnforcedStyle: percent

# クラス内のクラスなどを定義する際の形式の強制無効
ClassAndModuleChildren:
  Enabled: false

# Rspecのexampleの数を制限しない
RSpec/ExampleLength:
  Enabled: false

# 複数行のテストがかける
RSpec/MultipleExpectations:
  Enabled: false

# ワードを制限しない
RSpec/ContextWording:
  Enabled: false

# let!をつかるようにする
RSpec/LetSetup:
  Enabled: false

# ネストの深さを制限しない
RSpec/NestedGroups:
  Enabled: false
