# This is a basic workflow to help you get started with Actions

name: Rails CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  rspec:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Make Env file
        shell: bash
        run: cp compose.env.test compose.env
      - name: Setup docker
        shell: bash
        run: |
          docker-compose build
          docker-compose up -d
      # Runs a set of commands using the runners shell
      - name: Make database
        run: |
          docker-compose run rails rake db:create    
          docker-compose run rails rake db:migrate
      - name: Run Rspec
        run: |
          docker-compose run rails rspec
