name: Rails CI/CD
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make Env file
        shell: bash
        run: cp compose.env.test compose.env
      - name: Setup docker
        shell: bash
        run: |
          docker-compose build
          docker-compose up -d
      - name: Make database
        run: |
          docker-compose run rails rake db:create
          docker-compose run rails rake db:migrate
      - name: Run Rspec
        run: |
          docker-compose run rails rspec
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: ./rails/coverage/
